FROM python:3.8

WORKDIR /app

COPY main.py .

RUN pip install confluent-kafka
COPY requirements.txt .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt
# Запускаємо FastAPI за допомогою uvicorn при старті контейнера

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]