FROM python:3.9-slim

WORKDIR /app

COPY . .

RUN pip install confluent-kafka
RUN pip install --no-cache-dir -r requirements.txt
# Запускаємо обробку повідомлень при старті контейнера
CMD ["python", "./purchase.py"]
